SELECT YEAR(A.SALES_DATE) AS YEAR, MONTH(A.SALES_DATE) AS MONTH, A.GENDER, COUNT(DISTINCT A.USER_ID) AS USERS FROM
(SELECT S.SALES_DATE, S.USER_ID, U.GENDER FROM ONLINE_SALE AS S
JOIN USER_INFO AS U
ON S.USER_ID = U.USER_ID) AS A
WHERE GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER