SELECT A.CAR_ID, A.CAR_TYPE, ROUND((A.DAILY_FEE * (1 - B.DISCOUNT_RATE / 100) * 30),0) AS FEE FROM
     (SELECT CAR_ID, CAR_TYPE, DAILY_FEE FROM CAR_RENTAL_COMPANY_CAR 
      WHERE CAR_TYPE IN ('세단','SUV')
      AND CAR_ID NOT IN (SELECT DISTINCT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                         WHERE START_DATE < '2022-12-00' AND END_DATE > '2022-11-00')) AS A               
JOIN (SELECT CAR_TYPE, DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
      WHERE CAR_TYPE IN ('세단','SUV')
      AND DURATION_TYPE = '30일 이상') AS B      
ON A.CAR_TYPE = B.CAR_TYPE
WHERE ROUND((A.DAILY_FEE * (1 - B.DISCOUNT_RATE / 100) * 30),0) >= 500000 
AND ROUND((A.DAILY_FEE * (1 - B.DISCOUNT_RATE / 100) * 30),0) < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC



# SELECT distinct c.CAR_ID, c.CAR_TYPE, round(c.DAILY_FEE*30*(100-p.DISCOUNT_RATE)/100) FEE
# from CAR_RENTAL_COMPANY_CAR c join (select CAR_TYPE, DISCOUNT_RATE
#                                     from CAR_RENTAL_COMPANY_DISCOUNT_PLAN
#                                     where DURATION_TYPE = '30일 이상') p
# on c.CAR_TYPE = p.CAR_TYPE
# where c.CAR_ID not in (select CAR_ID
#                        from CAR_RENTAL_COMPANY_RENTAL_HISTORY
#                        where END_DATE > '2022-11-00'
#                        and START_DATE < '2022-12-00')
# and c.CAR_TYPE in ('세단', 'SUV')
# having FEE >= 500000
# and FEE < 2000000
# order by FEE desc, c.CAR_TYPE, c.CAR_ID desc