SELECT DISTINCT A.CART_ID FROM CART_PRODUCTS AS A
INNER JOIN CART_PRODUCTS AS B
ON A.CART_ID = B.CART_ID AND ((A.NAME = 'Milk' AND B.NAME = 'Yogurt') OR (A.NAME = 'Yogurt' AND B.NAME = 'Milk'))
ORDER BY A.CART_ID ASC