SELECT F.FLAVOR FROM FIRST_HALF F
INNER JOIN ICECREAM_INFO I ON F.FLAVOR = I.FLAVOR
WHERE TOTAL_ORDER > 3000 
AND INGREDIENT_TYPE = 'fruit_based' 
ORDER BY TOTAL_ORDER DESC

# FIRST_HALF에 ICECREAM_INFO을 INNER JOIN 하여 FLAVOR가 일치하는 통합 테이블을 만든다
# WHERE절을 사용하여 조건을 걸어주고
# ORDER BY를 통해서 정렬한다