SELECT 
MONTH(START_DATE) AS MONTH,
CAR_ID,
COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN
(SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
 WHERE START_DATE >= '2022-08-01 00:00:00' AND START_DATE < '2022-11-01 00:00:00'
 GROUP BY CAR_ID
 HAVING COUNT(CAR_ID) >= 5
 ORDER BY CAR_ID)
AND MONTH(START_DATE) BETWEEN 8 AND 10
GROUP BY MONTH, CAR_ID
ORDER BY MONTH ASC, CAR_ID DESC