# SELECT CAR_ID, ROUND((SUM(DATEDIFF(START_DATE, END_DATE) + 1) / COUNT(CAR_ID)), 1) AS AVERAGE_DURATION 
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# GROUP BY CAR_ID
# HAVING AVERAGE_DURATION > 6
# ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC

SELECT CAR_ID, ROUND((SUM(DATEDIFF(end_date, start_date) + 1) / COUNT(CAR_ID)), 1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING AVERAGE_DURATION > 6
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC;