SELECT U.USER_ID, U.NICKNAME, B.TOTAL_SALES FROM USED_GOODS_USER AS U
JOIN (SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES FROM USED_GOODS_BOARD
WHERE STATUS = 'DONE'
GROUP BY WRITER_ID) AS B
ON B.WRITER_ID = U.USER_ID
HAVING B.TOTAL_SALES >= 700000
ORDER BY B.TOTAL_SALES ASC