SELECT T.AUTHOR_ID, T.AUTHOR_NAME, T.CATEGORY, SUM(T.SALES * T.PRICE) AS TOTAL_SALES FROM
(SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, S.SALES, B.PRICE FROM BOOK_SALES AS S
JOIN BOOK AS B ON S.BOOK_ID = B.BOOK_ID
JOIN AUTHOR AS A ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE SALES_DATE LIKE '2022-01%') AS T
GROUP BY T.AUTHOR_NAME, T.CATEGORY
ORDER BY T.AUTHOR_ID ASC, T.CATEGORY DESC