SELECT T.HISTORY_ID, ROUND(((T.RENTAL_SUM * T.DAILY_FEE) * ((100 - T.DISCOUNT_RATE) / 100)),0) AS FEE FROM
(SELECT A.HISTORY_ID, A.RENTAL_SUM, A.DAILY_FEE, IFNULL(B.DISCOUNT_RATE,0) AS DISCOUNT_RATE FROM
(SELECT 
H.HISTORY_ID,
(TIMESTAMPDIFF(DAY, H.START_DATE, H.END_DATE) + 1) AS RENTAL_SUM,
(CASE 
    WHEN TIMESTAMPDIFF(DAY, H.START_DATE, H.END_DATE) + 1 < 7 THEN 0
    WHEN TIMESTAMPDIFF(DAY, H.START_DATE, H.END_DATE) + 1 >= 7 AND
         TIMESTAMPDIFF(DAY, H.START_DATE, H.END_DATE) + 1 < 30 THEN 1
    WHEN TIMESTAMPDIFF(DAY, H.START_DATE, H.END_DATE) + 1 >= 30 AND
         TIMESTAMPDIFF(DAY, H.START_DATE, H.END_DATE) + 1 < 90 THEN 2
    WHEN TIMESTAMPDIFF(DAY, H.START_DATE, H.END_DATE) + 1 >= 90 THEN 3
 END
) AS DISCOUNT_CASE,
R.DAILY_FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
JOIN CAR_RENTAL_COMPANY_CAR AS R
ON R.CAR_ID = H.CAR_ID
WHERE R.CAR_TYPE = '트럭') AS A
LEFT OUTER JOIN
(SELECT
(CASE 
    WHEN DURATION_TYPE = '7일 이상' THEN 1
    WHEN DURATION_TYPE = '30일 이상' THEN 2
    WHEN DURATION_TYPE = '90일 이상' THEN 3
 END
) AS DISCOUNT_CASE ,
DISCOUNT_RATE
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
WHERE CAR_TYPE = '트럭') AS B
ON A.DISCOUNT_CASE = B.DISCOUNT_CASE) AS T
ORDER BY ROUND(((T.RENTAL_SUM * T.DAILY_FEE) * ((100 - T.DISCOUNT_RATE) / 100)),1) DESC, T.HISTORY_ID DESC