SELECT A.PRODUCT_ID, A.PRODUCT_NAME, SUM(A.PRICE * A.AMOUNT) AS TOTAL_SALES FROM
(SELECT O.PRODUCE_DATE, O.PRODUCT_ID, P.PRODUCT_NAME, P.PRICE, O.AMOUNT  FROM FOOD_ORDER AS O
JOIN FOOD_PRODUCT AS P
ON O.PRODUCT_ID = P.PRODUCT_ID
HAVING O.PRODUCE_DATE LIKE '2022-05%') AS A
GROUP BY PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, A.PRODUCT_ID ASC