SELECT U.APNT_NO, U.PT_NAME, U.PT_NO, U.MCDP_CD, D.DR_NAME, U.APNT_YMD FROM
(SELECT A.APNT_YMD, A.APNT_NO, P.PT_NAME, P.PT_NO, A.MDDR_ID, A.APNT_CNCL_YN, A.MCDP_CD FROM APPOINTMENT AS A
JOIN PATIENT AS P
ON A.PT_NO = P.PT_NO) AS U
JOIN DOCTOR AS D
ON D.DR_ID = U.MDDR_ID
WHERE U.APNT_CNCL_YN = 'N'
AND U.APNT_YMD LIKE '2022-04-13%'
AND U.MCDP_CD = 'CS'
ORDER BY U.APNT_YMD ASC