SELECT DISTINCT H.CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
JOIN CAR_RENTAL_COMPANY_CAR AS C
ON H.CAR_ID = C.CAR_ID
WHERE C.CAR_TYPE = '세단'
AND DATE_FORMAT(H.START_DATE,'%Y-%m-%d') >= '2022-10-01'
AND DATE_FORMAT(H.START_DATE,'%Y-%m-%d') < '2022-11-01'
ORDER BY H.CAR_ID DESC
