SELECT R.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, ROUND(AVG(R.REVIEW_SCORE),2) AS SCORE FROM REST_REVIEW AS R
JOIN REST_INFO AS I
ON R.REST_ID = I.REST_ID
WHERE ADDRESS LIKE '서울%'
GROUP BY I.REST_NAME
ORDER BY SCORE DESC, I.FAVORITES DESC